import type { Project } from './types';

// Données projets — module pur (sans 'use client') : consommé par la section
// interactive (ProjectsSection) ET par le bloc SEO rendu côté serveur (page.tsx).
export const PROJECTS_DATA: Project[] = [
  {
    title:          'Arrakis Player Cards',
    description:    'Plateforme communautaire pour une association gaming de 2000 membres. Système de cartes joueurs façon FIFA, alimenté par les performances réelles en compétition.',
    contribution:   'Architecture complète, parseur Excel custom, algorithme de scoring calibré sur données réelles, animations Framer Motion, CI/CD Vercel.',
    tech:           ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Vercel'],
    highlights:     ['Livré seul de bout en bout', 'Données réelles', 'Déployé en production'],
    status:         'COMPLETED',
    memId:          'PRJ.001',
    classification: 'PRODUCTION',
    extractionTime: 600,
    github:         'https://github.com/Charkx/arrakis-cards',
    demo:           'https://arrakis-cards.vercel.app/',
    image:          '/projects/arrakis.webp',
    context:        'ASSO',
    short:          'Arrakis',
    probleme:       "Une association gaming de 2 000 membres suivait les performances de ses joueurs en compétition dans des fichiers Excel : aucune vue d'ensemble, aucun moyen pour un joueur de se situer ou de suivre sa progression.",
    solution:       "J'ai conçu et livré la plateforme seul, de bout en bout : parseur Excel custom pour ingérer les données existantes, algorithme de scoring calibré sur les performances réelles, cartes joueurs façon FIFA animées avec Framer Motion, base PostgreSQL et déploiement continu sur Vercel.",
    resultat:       "En production et utilisée par la communauté : chaque joueur a sa carte alimentée par ses vraies statistiques de compétition. Mon premier projet porté seul en conditions réelles, de la donnée brute au produit déployé.",
  },
  {
    title:          "L'Œil Artistique",
    description:    'Site vitrine moderne avec animations avancées, conçu et déployé de bout en bout.',
    contribution:   'Design, développement et déploiement complet.',
    tech:           ['Next.js', 'Tailwind CSS', 'GSAP', 'Vercel'],
    highlights:     ['Animations avancées', 'Performance', 'Déployé en production'],
    status:         'OPERATIONAL',
    memId:          'PRJ.002',
    classification: 'LIVE',
    extractionTime: 600,
    github:         'https://github.com/Charkx/oeilartistique',
    demo:           'https://oeilartistique.vercel.app',
    image:          '/projects/oeil-artistique.webp',
    context:        'PRO',
    short:          "L'Œil",
    probleme:       "Un projet professionnel : créer une vitrine en ligne à la hauteur d'une identité visuelle artistique — un site rapide, moderne, avec de vraies animations, à concevoir entièrement.",
    solution:       "J'ai porté le projet du design au déploiement : maquette, développement Next.js + Tailwind CSS, animations GSAP orchestrées au scroll, optimisation des médias et mise en ligne sur Vercel.",
    resultat:       "Site en ligne, performant et animé, livré en autonomie complète — du brief à la production.",
  },
  {
    title:          'Expérience 3D Interactive',
    description:    'Expérience interactive 3D navigable directement dans le navigateur (ce portfolio même).',
    contribution:   'Scènes WebGL temps réel, interactions et animations 3D, intégration React.',
    tech:           ['Three.js', 'React Three Fiber', 'React'],
    highlights:     ['WebGL', 'Animations 3D temps réel'],
    status:         'ACTIVE',
    memId:          'PRJ.003',
    classification: 'EXPERIMENTAL',
    extractionTime: 600,
    github:         'https://github.com/Charkx/components_library_react',
    demo:           '',
    image:          '/projects/portfolio-3d.webp',
    context:        'PERSO',
    short:          'Exp. 3D',
    probleme:       "Comment se démarquer parmi des centaines de portfolios de développeurs ? Plutôt que de lister mes compétences front, j'ai voulu que le site lui-même en soit la démonstration : une expérience 3D temps réel navigable au scroll, directement dans le navigateur.",
    solution:       "Scène WebGL pilotée par le scroll (React Three Fiber) : un hologramme humain traversé de station en station, modules 3D interactifs par section, shaders custom, design sonore en synthèse WebAudio — intégré à Next.js avec de vrais replis d'accessibilité (reduced-motion, navigation clavier, contenu rendu côté serveur).",
    resultat:       "Le site que vous êtes en train de visiter : assets 3D compressés (Draco), SEO server-side, et un terrain d'expérimentation permanent pour le rendu temps réel.",
  },
  {
    title:          'Poly\'tendo',
    description:    'BDE Polytech Marseille : site web vitrine pour la campagne de BDE.',
    contribution:   'React, Tailwind CSS, animations GSAP, intégration de contenus dynamiques.',
    tech:           ['React', 'Tailwind CSS', 'GSAP'],
    highlights:     ['React', 'IU/UX'],
    status:         'ACTIVE',
    memId:          'PRJ.004',
    classification: 'EXPERIMENTAL',
    extractionTime: 600,
    github:         'https://github.com/Charkx/Poly-tendo',
    demo:           'https://poly-tendo.vercel.app/',
    image:          '/projects/polytendo.webp',
    context:        'ECOLE',
    short:          "Poly'tendo",
    probleme:       "Campagne BDE à Polytech Marseille : l'équipe avait besoin d'un site vitrine marquant pour porter sa campagne, dans le temps court imposé par l'événement.",
    solution:       "Développement React + Tailwind CSS, animations GSAP pour donner l'énergie de la campagne, intégration des contenus de l'équipe (programme, membres, événements).",
    resultat:       "Site en ligne pendant la campagne, vitrine de l'équipe auprès des étudiants.",
  },
];
